### ISSUE TITLE
Mapa dos stackholders

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/nota_solidaria#18]

**Comment by Gisellicwb** [comment]
Stakeholders:
Prefeitura de Curitiba
Code for Curitiba
Instituições de Caridade
Empresas emissoras de nota fiscais

**Comment by thierrydelbart** [comment]
Na verdade a prefeitura de Curitiba não tem nada a ver eu acho. É o estado do Paraná e a Secretária da  Fazenda que gerencia o programa Nota Paraná. Vou convidar eles para a apresentação da Alpha amanhã.

Mas um coisa interessante na tua lista são as empresas emissoras de cupons fiscais, talvez deveríamos incluir uma ou duas delas na validação... (não sei muito bem porque mas teoricamente deveríamos).

**Comment by thierrydelbart** [comment]
Copiado no README
