### ISSUE TITLE
Fazer uma pesquisa de validação da ideia

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/nota_solidaria#2]

**Comment by Gisellicwb** [comment]
Povo/Thierry,
Como falamos, segue roteiro de pesquisa, serve mais como guia de orientação para a pesquisa.
O ideal é que seja feito com um minimo de 10 usuarios / 5 instituições de caridade.
Anotar sexo, idade, se é economicamente ativo, se tem o habito de colocar cpf nas notas, frequencia e local que mais realiza compras

 Pesquisa
A pesquisa tem foco em 2 clientes: o usuário do aplicativo e a instituição de caridade.

Objetivo pesquisa usuário:
Identificar usabilidade e interação do usuário com o aplicativo.
Finalidade:
Identificar se o seria um app tem uma proposta de valor tanto para o usuário quanto para a instituição.
Validar se app atende ao requisito mínimo no ponto de vista do usu/instituição: scanear notas fiscais.
Identificar os pontos fortes do app, apelos para futura venda, valor agregado, características mínimas;
Identificar formato ideal para campanha de lançamento e venda do app para outras instituições resultando em parcerias futuras para o code.

Usuário:
• Explicar o objetivo do app  (scanear notas fiscais e contribuir com doação para instituições de caridade) não falar do detalhe das telas antes do uso, deixar que ele descubra o app. 
• Ter notas fiscais que funcionem a mão para o teste.
• Colocar o usuário para fazer o teste no celular do pesquisador mesmo (a versão alpha requer configurações extras para instalar , o que não seria bom o usuário vivenciar uma vez que não é o que acontecera com a versão oficial)
• Colocar o aplicativo para teste pelo usuário e identificar:
o   - Foi fácil usar o aplicativo? Está intuitivo, fácil e rápido de usar?
o   - Teve alguma dificuldade, qual?
o   - De forma geral, atende a necessidade de scanear notas fiscais?
o   - É um aplicativo que você usaria sempre? Se não, o que falta para você utilizar sempre?
o   - De forma geral, o que mais te chamou a atenção?

Instituição de caridade:
• Seguir os mesmos testes de usuário no app acima, anotar respostas;

• Alem das perguntas acima, realizar estas perguntas extras:
o   Os voluntários que hoje ajudam a instituição a colher notas fiscais, usariam este aplicativo e porque?
o   Há algum ponto de melhoria?

• Após uso do app, apresentar as etapas de interação do app com a instituição (tabelas Thierry) e identificar:
o   As informações disponibilizadas são importantes ?
o   Quais são as informações que sua instituição precisaria a partir deste aplicativo (pedir para confirmar quais o app já tem):
 Informações mínimas + benefícios;
 Informações desejadas + beneficios;
 Informações extras + beneficios.
o   Quais são as dificuldades atuais da instituição com a coleta das notas fiscais?

**Comment by thierrydelbart** [comment]
Copiado no README
