### ISSUE TITLE
Fazer jornada do usuario

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/nota_solidaria#21]

**Comment by thierrydelbart** [comment]
Eu vou tentar responder nesta issue a issue #19: _definir o usuário alvo_

**Comment by thierrydelbart** [comment]
No caso do projeto ACRIDAS temos dois usuários:
- o doador (usuário que vai doar uma NF)
- o agente da ONG (usuário que vai validar a doação)

Vamos ver as diferentes jornadas para ambos.

## O Doador

### No app
1. Na primeira abertura do app, o usuário é encaminhado para a página para preencher o perfil
2. A página de Scanner para escanear uma nova NF e dois botões para ir na página do perfil ou para a página de doação manual. Em caso de leitura de uma nova NF, uma popup pede confirmação da doação da NF.
3. A página de doação manual permite preencher os campos: valor da NF, data de emissão da NF, chave da NF e CNPJ do emissor da NF. Um botão "Doar" valida a doação e reinicializa o formulário. Um botão "Escanear" permiti voltar a página para escanear. Um botão perfil permiti acessar a página do perfil.
4. A página do perfil permiti:  editar os campos do perfil (nome - obrigatório - , email e telefone), ver a lista das NF doadas, conectar a conta com uma conta Facebook

### A ONG

Depende do #38

**Comment by Gisellicwb** [comment]
- Potencial Cliente : Segundo Patricia, a maior quantidade de usuários serão os que já são voluntários na Acridas, por isso a linguagem do site é menos informal, como se já conhecessemos o "cliente";

**Comment by thierrydelbart** [comment]
Ta certa @Gisellicwb
