### ISSUE TITLE
Mapa da proposição de valor

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/nota_solidaria#7]

**Comment by thierrydelbart** [comment]
@Gisellicwb pode colocar a foto aqui?

**Comment by adaolima** [comment]
Canvas Proposta de Valor
![file_004](https://cloud.githubusercontent.com/assets/16966882/15405393/0c4ab584-1dd8-11e6-9b9c-2ca974f3dc51.jpeg)
![file_001](https://cloud.githubusercontent.com/assets/16966882/15405394/0c4acaba-1dd8-11e6-9802-5a3ae7b2883a.jpeg)
![file_003](https://cloud.githubusercontent.com/assets/16966882/15405395/0c4fc0ba-1dd8-11e6-8199-07ed81ea7eaf.jpeg)
![file_000](https://cloud.githubusercontent.com/assets/16966882/15405397/0c5491b2-1dd8-11e6-97a8-e84beb301418.jpeg)
![file_002](https://cloud.githubusercontent.com/assets/16966882/15405398/0c560196-1dd8-11e6-87f4-a6ae65cb6098.jpeg)
![file_005](https://cloud.githubusercontent.com/assets/16966882/15405396/0c53c82c-1dd8-11e6-9fc2-b3e4147ae67b.jpeg)

**Comment by thierrydelbart** [comment]
Ótimo @adaolima
