### ISSUE TITLE
Definir Nome, Descrição curta, Descrição do projeto

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/nota_solidaria#8]

**Comment by Gisellicwb** [comment]
O que é?

Aplicativo que faz o repasse rápido de valores do programa Nota Solidária Paraná para instituições de caridade.

A primeira instituição beneficiada é a Acridas, que atende crianças, adolescentes, famílias em situações de risco pessoal e social que fazem com que pessoas sejam retiradas de seus lares ou sofram situações de abandono.

**Comment by Gisellicwb** [comment]
![pitch notasolidaria](https://cloud.githubusercontent.com/assets/19316199/15794944/2f96cf52-29c5-11e6-9579-e3e0efdc88c9.png)

**Comment by thierrydelbart** [comment]
não é Nota Solidária Paraná, é Nota Paraná, né?

**Comment by Gisellicwb** [comment]
[Notasolidaria.docx](https://github.com/CodeForCuritiba/nota_solidaria/files/336204/Notasolidaria.docx)

**Comment by Gisellicwb** [comment]
Atualizado! =)
